"""Generate all tables

Revision ID: 3993b9f492d5
Revises: 
Create Date: 2024-12-21 12:19:21.103249

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3993b9f492d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_name', sa.String(255), nullable=True),
    sa.Column('location', sa.String(255), nullable=True),
    sa.Column('city', sa.String(255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garages_id'), 'garages', ['id'], unique=False)
    op.create_index(op.f('ix_garages_name'), 'garages', ['garage_name'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(255), nullable=True),
    sa.Column('model', sa.String(255), nullable=True),
    sa.Column('productionYear', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(255), nullable=True),
    sa.Column('garages', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['garages'], ['garages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_license_plate'), 'cars', ['license_plate'], unique=True)
    op.create_index(op.f('ix_cars_make'), 'cars', ['make'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_table('maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('garage_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(255), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenances_id'), 'maintenances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenances_id'), table_name='maintenances')
    op.drop_table('maintenances')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index(op.f('ix_cars_make'), table_name='cars')
    op.drop_index(op.f('ix_cars_license_plate'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_garages_name'), table_name='garages')
    op.drop_index(op.f('ix_garages_id'), table_name='garages')
    op.drop_table('garages')
    # ### end Alembic commands ###
