"""Changes to car files

Revision ID: 56b76f715031
Revises: 67e211d9d812
Create Date: 2024-12-21 16:10:29.844411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56b76f715031'
down_revision: Union[str, None] = '67e211d9d812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_garage',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ),
    sa.PrimaryKeyConstraint('car_id', 'garage_id')
    )
    op.drop_constraint('cars_ibfk_1', 'cars', type_='foreignkey')
    op.drop_column('cars', 'garageIds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('garageIds', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cars_ibfk_1', 'cars', 'garages', ['garageIds'], ['id'])
    op.drop_table('car_garage')
    # ### end Alembic commands ###
