"""adding foreign key

Revision ID: 5ad29b60dfa0
Revises: 56b76f715031
Create Date: 2024-12-21 16:29:19.352992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad29b60dfa0'
down_revision: Union[str, None] = '56b76f715031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('garageId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cars', 'garages', ['garageId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'garageId')
    # ### end Alembic commands ###
