"""Rename car model-more chnages5

Revision ID: 67e211d9d812
Revises: d2e6ecad378b
Create Date: 2024-12-21 15:49:06.433834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67e211d9d812'
down_revision: Union[str, None] = 'd2e6ecad378b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('garageIds', sa.Integer(), nullable=True))
    op.drop_constraint('cars_ibfk_1', 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'garages', ['garageIds'], ['id'])
    op.drop_column('cars', 'garageId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('garageId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key('cars_ibfk_1', 'cars', 'garages', ['garageId'], ['id'])
    op.drop_column('cars', 'garageIds')
    # ### end Alembic commands ###
