"""some changes again

Revision ID: 7d0b637df75b
Revises: 612e9e5dce4c
Create Date: 2024-12-21 23:13:29.326468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d0b637df75b'
down_revision: Union[str, None] = '612e9e5dce4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('garageIds', sa.JSON(), nullable=True))
    op.drop_constraint('cars_ibfk_1', 'cars', type_='foreignkey')
    op.drop_column('cars', 'garageId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('garageIds', sa.JSON(), nullable=True))
    op.create_foreign_key('cars_ibfk_1', 'cars', 'garages', ['garageId'], ['id'])
    op.drop_column('cars', 'garageIds')
    # ### end Alembic commands ###
