"""car table alteration

Revision ID: 96b03d3b690d
Revises: a0aed6d396b8
Create Date: 2024-12-21 18:02:41.018193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96b03d3b690d'
down_revision: Union[str, None] = 'a0aed6d396b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_garage',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('car_id', 'garage_id')
    )
    op.drop_constraint('cars_ibfk_1', 'cars', type_='foreignkey')
    op.drop_column('cars', 'garageId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('garageId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cars_ibfk_1', 'cars', 'garages', ['garageId'], ['id'])
    op.drop_table('car_garage')
    # ### end Alembic commands ###
