"""Rename car model-more chnages3

Revision ID: 99f5cacbb74b
Revises: 16fe05b82c8e
Create Date: 2024-12-21 15:13:52.337327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f5cacbb74b'
down_revision: Union[str, None] = '16fe05b82c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
