"""Remove car_garage table and update Car-Garage relationship

Revision ID: a0aed6d396b8
Revises: 5ad29b60dfa0
Create Date: 2024-12-21 16:37:21.110254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a0aed6d396b8'
down_revision: Union[str, None] = '5ad29b60dfa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_garage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_garage',
    sa.Column('car_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('garage_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name='car_garage_ibfk_1'),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], name='car_garage_ibfk_2'),
    sa.PrimaryKeyConstraint('car_id', 'garage_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
