"""car table alteration2

Revision ID: cc6be9ebcada
Revises: 96b03d3b690d
Create Date: 2024-12-21 21:45:12.847204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6be9ebcada'
down_revision: Union[str, None] = '96b03d3b690d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('garageId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cars', 'garages', ['garageId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'garageId')
    # ### end Alembic commands ###
