"""some changes again 2

Revision ID: dc91cd696356
Revises: 7d0b637df75b
Create Date: 2024-12-22 22:21:12.981664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc91cd696356'
down_revision: Union[str, None] = '7d0b637df75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('car_id', table_name='maintenances')
    op.drop_index('garage_id', table_name='maintenances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('garage_id', 'maintenances', ['garageId'], unique=False)
    op.create_index('car_id', 'maintenances', ['carId'], unique=False)
    # ### end Alembic commands ###
