"""Add foreign key constraint on carId

Revision ID: e1c0ea5409ac
Revises: dc91cd696356
Create Date: 2024-12-22 22:31:16.242561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c0ea5409ac'
down_revision: Union[str, None] = 'dc91cd696356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
